services:
  postgres:
    image: postgres:15
    container_name: imdb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb_reddit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./requirements.txt:/requirements.txt

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: imdb_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.7.2
    container_name: imdb_airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/imdb_reddit
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
    entrypoint: >
      bash -c "
        echo 'Waiting for Postgres...';
        until pg_isready -h postgres -p 5432; do sleep 2; done;
        airflow db upgrade;
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com --force;
        airflow scheduler &
        airflow webserver
      "

volumes:
  postgres_data:

